yarn add \
    @babel/core \
    @babel/plugin-proposal-class-properties \
    @babel/plugin-proposal-nullish-coalescing-operator \
    @babel/plugin-proposal-optional-chaining \
    @emotion/core \
    @emotion/styled \
    @loadable/component \
    @mdx-js/mdx \
    @mdx-js/react \
    @types/cannon \
    @types/loadable__component \
    @types/p5 \
    @types/react \
    @types/react-helmet \
    cannon \
    core-js \
    eslint-scope \
    gatsby \
    gatsby-image \
    gatsby-plugin-advanced-sitemap \
    gatsby-plugin-catch-links \
    gatsby-plugin-emotion \
    gatsby-plugin-google-analytics \
    gatsby-plugin-manifest \
    gatsby-plugin-mdx \
    gatsby-plugin-netlify \
    gatsby-plugin-netlify-cache \
    gatsby-plugin-offline \
    gatsby-plugin-react-helmet \
    gatsby-plugin-react-helmet-canonical-urls \
    gatsby-plugin-robots-txt \
    gatsby-plugin-root-import \
    gatsby-plugin-sharp \
    gatsby-plugin-typescript \
    gatsby-plugin-webpack-bundle-analyzer \
    gatsby-remark-images \
    gatsby-remark-relative-images \
    gatsby-source-filesystem \
    gatsby-transformer-sharp \
    graphql \
    p5 \
    react \
    react-dom \
    react-helmet \
    react-three-fiber \
    three \
    typescript \
    unstated-next \
    webpack